#!/usr/bin/env bash
# Artemis installer — pipe-to-bash friendly.
#
#   curl -fsSL https://raw.githubusercontent.com/nesdeq/artemis/main/install.sh | bash
#
# Re-running this script updates an existing checkout and re-installs deps.
#
# Overrides (export before piping):
#   ARTEMIS_HOME    where to clone the repo   (default: $HOME/.local/share/artemis)
#   BIN_DIR         where to place the launcher  (default: $HOME/.local/bin)
#   ARTEMIS_REPO    git url to clone           (default: nesdeq/artemis on GitHub)

set -euo pipefail

ARTEMIS_HOME="${ARTEMIS_HOME:-$HOME/.local/share/artemis}"
BIN_DIR="${BIN_DIR:-$HOME/.local/bin}"
REPO_URL="${ARTEMIS_REPO:-https://github.com/nesdeq/artemis.git}"

say() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m!!\033[0m %s\n' "$*" >&2; exit 1; }

command -v python3 >/dev/null 2>&1 || die "python3 is required"
command -v git     >/dev/null 2>&1 || die "git is required"

if [ -d "$ARTEMIS_HOME/.git" ]; then
    say "Updating existing checkout at $ARTEMIS_HOME"
    git -C "$ARTEMIS_HOME" pull --ff-only
elif [ -e "$ARTEMIS_HOME" ]; then
    die "$ARTEMIS_HOME exists and is not a git repo. Move it aside and rerun."
else
    say "Cloning $REPO_URL into $ARTEMIS_HOME"
    mkdir -p "$(dirname "$ARTEMIS_HOME")"
    git clone --depth 1 "$REPO_URL" "$ARTEMIS_HOME"
fi

say "Creating venv at $ARTEMIS_HOME/.venv"
python3 -m venv "$ARTEMIS_HOME/.venv"

say "Installing dependencies"
"$ARTEMIS_HOME/.venv/bin/pip" install --quiet --upgrade pip
"$ARTEMIS_HOME/.venv/bin/pip" install --quiet -r "$ARTEMIS_HOME/requirements.txt"

say "Writing launcher to $BIN_DIR/arti"
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/arti" <<EOF
#!/usr/bin/env bash
# Artemis launcher (generated by install.sh)
cd "$ARTEMIS_HOME" || exit 1
exec ".venv/bin/python" "tui.py" "\$@"
EOF
chmod +x "$BIN_DIR/arti"

cat <<EOF

  Artemis is installed.

  Ensure $BIN_DIR is on your PATH, then run:
      arti

  Set credentials in your shell rc (~/.bashrc, ~/.zshrc, ~/.config/fish/config.fish):
      export OPENAI_API_KEY=...        # required
      export SERP_API_KEY=...          # optional, for web search (serper.dev)
      export ENCKEY=...                # encryption key for personal memory
      export HUE_BRIDGE_IP=...         # optional, Philips Hue bridge LAN IP

  Data and history live in ~/.artemis (encrypted memory, command history, exports).

  Uninstall:
      rm -rf "$ARTEMIS_HOME" "$BIN_DIR/arti"
      rm -rf ~/.artemis    # also wipes encrypted memory and history

EOF
